-- CREATE TABLE IF NOT EXISTS URL_TABLE (
--     URL VARCHAR(255) NOT NULL,
--     URL_ID VARCHAR(255) PRIMARY KEY
-- );

CREATE TABLE IF NOT EXISTS URL_TABLE (
    id serial NOT NULL PRIMARY KEY,
    URL text,
    URL_ID character(5)
);
